version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  pre_build:
    commands:
    #to install libraries, omit pre_build section if no python library dependency
      - pip install -r ./requirements.txt --target ./
      
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket <<Code bucket>> --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
    - template.yaml
